// ── Outlook email feed ────────────────────────────────────────────────────────
// Source: Creative Campus folder — Bond, Curtin, Edith Cowan, La Trobe,
//         UWA, RMIT (+ Inbox for Swinburne/Torrens/MDS contacts)
// Last fetched: 2026-06-02
// Note: Torrens University and Media Design School are combined under one institution.
// To refresh: open a conversation with Claude and say "sync my emails"
// Folder note: 'Swinburne' and 'Torrens/MDS' folders could not be resolved by
//   the connector — the / in the folder name blocks lookup. To fix, rename the
//   folder to 'Torrens MDS' (no slash) in Outlook and Claude can sync it directly.

export const LAST_FETCHED = '2026-06-02'

export const DOMAIN_MAP = {
  'latrobe.edu.au':           'La Trobe University',
  'sa.gov.au':                'SA Government — Education',
  'curtin.edu.au':            'Curtin University',
  'curtincollege.edu.au':     'Curtin University',
  'guild.uwa.edu.au':         'University of Western Australia',
  'uwa.edu.au':               'University of Western Australia',
  'rmit.edu.au':              'RMIT University',
  'westernsydney.edu.au':     'Western Sydney University',
  'swin.edu.au':              'Swinburne University',
  'torrens.edu.au':           'Torrens University & Media Design School',
  'mediadesignschool.com':    'Torrens University & Media Design School',
  'nmtafe.wa.edu.au':         'North Metropolitan TAFE',
  'bond.edu.au':              'Bond University',
  'ecu.edu.au':               'Edith Cowan University',
  'ute.edu.sg':               'ITE Singapore',
  'uts.edu.au':               'University of Technology Sydney',
  'unsw.edu.au':              'UNSW Sydney',
  'unimelb.edu.au':           'University of Melbourne',
  'monash.edu':               'Monash University',
  'anu.edu.au':               'Australian National University',
  'griffith.edu.au':          'Griffith University',
  'qut.edu.au':               'Queensland University of Technology',
  'unisa.edu.au':             'University of South Australia',
  'flinders.edu.au':          'Flinders University',
}

export const EMAILS = [

  // ── BOND UNIVERSITY ─────────────────────────────────────────────────────────
  {
    id: 'bond_ai_enterprise_0526',
    date: '2026-05-26',
    subject: 'Business - Enterprise AI discussion',
    institution: 'Bond University',
    primaryEmail: 'adgepp@bond.edu.au',
    recipients: ['adgepp@bond.edu.au', 'ngreenwa@bond.edu.au', 'lgowthor@bond.edu.au', 'rgauld@bond.edu.au'],
    summary: 'Follow-up from campus visit discussing Bond\'s Enterprise AI Program. Kim Burdett leading, Al CC\'d. Opportunities identified for Adobe to partner and support success across student and staff programs.',
    objective: 'AI Innovation and Leadership',
  },
  {
    id: 'bond_confirmed_lunch_0518',
    date: '2026-05-18',
    subject: 'CONFIRMED - campus presentation and updates',
    institution: 'Bond University',
    primaryEmail: 'jbrand@bond.edu.au',
    recipients: ['jbrand@bond.edu.au', 'shosalov@bond.edu.au'],
    summary: 'Jeff Brand (Deputy Provost) confirmed campus visit for lunch and presentation. Sona Hosalov CC\'d. Partnership updates and new tool demos planned.',
    objective: 'Awareness',
  },
  {
    id: 'bond_craig_sims_intro_0507',
    date: '2026-05-07',
    subject: 'Introducing Craig Sims',
    institution: 'Bond University',
    primaryEmail: 'csims@bond.edu.au',
    recipients: ['csims@bond.edu.au'],
    summary: 'Craig Sims (deputy convenor, Collaboration for Global Change subject) introduced himself following Bond\'s presentation. Works closely with Dan Brennan. Keen to stay in touch and explore further Adobe collaboration.',
    objective: 'Curriculum Support',
  },
  {
    id: 'bond_date_visit_may_0511',
    date: '2026-05-11',
    subject: 'Date in May for visit - Adobe',
    institution: 'Bond University',
    primaryEmail: 'rgauld@bond.edu.au',
    recipients: ['rgauld@bond.edu.au', 'BBSEA@bond.edu.au'],
    summary: 'Logistics confirmed for campus visit on 21 May. Robin Gauld (Dean) and admin confirmed boardroom with screen. Accreditation commitments may affect Robin\'s attendance.',
    objective: 'Awareness',
  },
  {
    id: 'bond_reimagining_assessment_0423',
    date: '2026-04-23',
    subject: 'Reimagining assessment with creativity and AI — Bond University',
    institution: 'Bond University',
    primaryEmail: 'dbrennan@bond.edu.au',
    recipients: ['dbrennan@bond.edu.au', 'csims@bond.edu.au', 'jbrand@bond.edu.au'],
    summary: 'Dan Brennan forwarding Adobe/Bond AI assessment collaboration thread. Jeff Brand CC\'d back in. Joint project underway on reimagining creative assessments using Adobe + AI tools.',
    objective: 'AI Innovation and Leadership',
  },
  {
    id: 'bond_innovation_cafe_accept_0423',
    date: '2026-04-23',
    subject: 'Bond - Adobe Innovation Café — accepted',
    institution: 'Bond University',
    primaryEmail: 'dbrennan@bond.edu.au',
    recipients: ['dbrennan@bond.edu.au'],
    summary: 'Daniel Brennan accepted Innovation Café event invite.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'bond_social_assets_0414',
    date: '2026-04-14',
    subject: 'Social media assets + run of the show',
    institution: 'Bond University',
    primaryEmail: 'dbrennan@bond.edu.au',
    recipients: ['dbrennan@bond.edu.au', 'csims@bond.edu.au', 'jbrand@bond.edu.au'],
    summary: 'Dan Brennan confirmed a great student submissions session for the Innovation Café. Manuela Franceschini coordinating social media assets and event run of show.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'bond_fsd_dean_intro_0416',
    date: '2026-04-16',
    subject: 'Adobe digital introduction — Faculty of Society and Design',
    institution: 'Bond University',
    primaryEmail: 'FSDdean@bond.edu.au',
    recipients: ['FSDdean@bond.edu.au'],
    summary: 'Lara Campese (EA to Executive Dean) coordinating introductory meeting with Prof Derek Carson. Meeting confirmed via online invite.',
    objective: 'Awareness',
  },

  // ── CURTIN UNIVERSITY ────────────────────────────────────────────────────────
  {
    id: 'curtin_nextsteps_matt_0529',
    date: '2026-05-29',
    subject: 'Curtin - Adobe - next steps',
    institution: 'Curtin University',
    primaryEmail: 'matt.reed@curtin.edu.au',
    recipients: ['matt.reed@curtin.edu.au'],
    summary: 'Matt Reed requesting Curtin IT team access AI tools via work email rather than personal accounts. Asking Al to liaise with DTS directly rather than approaching from Matt\'s side.',
    objective: 'IT/Tech Support',
  },
  {
    id: 'curtin_curriculum_connect_0529',
    date: '2026-05-29',
    subject: 'Connect — Adobe & Curtin curriculum innovation',
    institution: 'Curtin University',
    primaryEmail: 'siobhan.unwin@curtin.edu.au',
    recipients: ['siobhan.unwin@curtin.edu.au', 'adrianne.evans@curtin.edu.au', 'bobby.cooper@curtin.edu.au'],
    summary: 'Introduction to Curtin curriculum innovation team — Siobhan Unwin, Adrianne Evans, Bobby Cooper. Referencing prior work with Manuela Franceschini. Thread active into early June with multiple replies.',
    objective: 'Curriculum Support',
  },
  {
    id: 'curtin_names_license_0514',
    date: '2026-05-14',
    subject: 'Trial license names — Curtin AI project',
    institution: 'Curtin University',
    primaryEmail: 'matt.reed@curtin.edu.au',
    recipients: ['matt.reed@curtin.edu.au', 'richard.blythe@curtin.edu.au'],
    summary: 'Kim requesting names for trial AI tool licenses. Prof Richard Blythe (Pro Vice Chancellor) responding in Matt\'s absence. Two options discussed: via Curtin IT console or personal Adobe accounts.',
    objective: 'IT/Tech Support',
  },
  {
    id: 'curtin_acrobat_sign_0507',
    date: '2026-05-07',
    subject: 'Curtin University | Adobe Acrobat Sign project status update',
    institution: 'Curtin University',
    primaryEmail: 'ben.connolly@curtin.edu.au',
    recipients: ['ben.connolly@curtin.edu.au', 'jared.derksen@curtin.edu.au'],
    summary: 'Ben Connolly confirming Acrobat Sign professional services engagement is wrapping up. Adobe team standing down on follow-up — Curtin will reach out when ready to proceed.',
    objective: 'IT/Tech Support',
  },
  {
    id: 'curtin_asu_ai_proposal_0429',
    date: '2026-04-29',
    subject: 'Call for Proposals: ASU AI - Student Experience',
    institution: 'Curtin University',
    primaryEmail: 'richard.blythe@curtin.edu.au',
    recipients: ['richard.blythe@curtin.edu.au', 'matt.reed@curtin.edu.au'],
    summary: 'Kim sharing ASU AI Student Experience partnership proposal opportunity. Richard Blythe and Matt Reed to consider a joint submission. Lighthearted tone — scooter reference running joke.',
    objective: 'AI Innovation and Leadership',
  },
  {
    id: 'curtin_college_training_0422',
    date: '2026-04-22',
    subject: 'Curtin College Adobe Express Staff Training',
    institution: 'Curtin University',
    primaryEmail: 'Ajay.Karia@curtincollege.edu.au',
    recipients: ['Ajay.Karia@curtincollege.edu.au', 'julie.robertson@curtincollege.edu.au'],
    summary: 'Al delivered interactive Adobe Express training for Curtin College staff. Ajay Karia and Julie Robertson leading. Participants keen to integrate into teaching — requesting follow-up session on infographics, talking avatars, and video editing.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'curtin_wil_fiona_0415',
    date: '2026-04-15',
    subject: 'Possible Adobe WIL opportunities',
    institution: 'Curtin University',
    primaryEmail: 'fiona.harman@curtin.edu.au',
    recipients: ['fiona.harman@curtin.edu.au'],
    summary: 'Dr Fiona Paraskos (WIL lead) sending internship job ad template and partnership guide following meeting. Exploring Work Integrated Learning opportunities between Adobe and Curtin.',
    objective: 'Staff and Student Engagement',
  },

  // ── EDITH COWAN UNIVERSITY ────────────────────────────────────────────────────
  {
    id: 'ecu_dataset_security_0521',
    date: '2026-05-21',
    subject: 'Quick check: Adobe dataset report',
    institution: 'Edith Cowan University',
    primaryEmail: 's.bandaranayake@ecu.edu.au',
    recipients: ['s.bandaranayake@ecu.edu.au', 'leeann.mitchell@ecu.edu.au'],
    summary: 'Sachi Bandaranayake querying an Adobe marketing dataset that appeared on a security forum. Al confirmed it had been reviewed by the security team and posed no risk. Sachi satisfied with response.',
    objective: 'IT/Tech Support',
  },
  {
    id: 'ecu_qbr_notes_0507',
    date: '2026-05-07',
    subject: 'QBR meeting notes',
    institution: 'Edith Cowan University',
    primaryEmail: 's.bandaranayake@ecu.edu.au',
    recipients: ['s.bandaranayake@ecu.edu.au', 'k.abbott@ecu.edu.au'],
    summary: 'Sachi requesting QBR meeting highlights from Al to document as evidence of ongoing contract value. Kate Abbott CC\'d.',
    objective: 'Awareness',
  },
  {
    id: 'ecu_ai_feature_kate_0501',
    date: '2026-05-01',
    subject: 'AI Beta feature enquiry',
    institution: 'Edith Cowan University',
    primaryEmail: 'k.abbott@ecu.edu.au',
    recipients: ['k.abbott@ecu.edu.au'],
    summary: 'Kate Abbott following up on AI Beta feature Al demonstrated to Kate and Ratna Selvaratnam. Requesting a screenshot or info page link.',
    objective: 'AI Innovation and Leadership',
  },
  {
    id: 'ecu_eculture_sponsorship_0415',
    date: '2026-04-15',
    subject: 'ECUlture 2026 Sponsorship Proposal — Centre for Learning & Teaching',
    institution: 'Edith Cowan University',
    primaryEmail: 'clt@ecu.edu.au',
    recipients: ['clt@ecu.edu.au'],
    summary: 'Wendy (Centre for Learning and Teaching) sending ECUlture 2026 sponsorship proposal. Al engaged via Kim Burdett referral. Meeting arranged with Ratna Selvaratnam and Wendy.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'ecu_amy_cairns_intro_0401',
    date: '2026-04-01',
    subject: 'Introduction: Amy Cairns (ECU) and Al Briggs (Adobe)',
    institution: 'Edith Cowan University',
    primaryEmail: 'a.cairns@ecu.edu.au',
    recipients: ['a.cairns@ecu.edu.au', 'k.abbott@ecu.edu.au'],
    summary: 'Kate Abbott introducing Amy Cairns (Manager, Digital and Information Literacy, ECU Library) to Al. Amy keen to facilitate student learning opportunities via the Library. Follow-up visit to City Campus being arranged.',
    objective: 'Curriculum Support',
  },
  {
    id: 'ecu_creative_campus_status_0325',
    date: '2026-03-25',
    subject: 'ECU Creative Campus status',
    institution: 'Edith Cowan University',
    primaryEmail: 's.bandaranayake@ecu.edu.au',
    recipients: ['s.bandaranayake@ecu.edu.au', 'r.selvaratnam@ecu.edu.au', 'k.abbott@ecu.edu.au'],
    summary: 'Sachi confirming deployment model agreed in yesterday\'s meeting — JIT licensing for students qualifies ECU as a Creative Campus without additional cost. Ratna Selvaratnam and Kate Abbott across this.',
    objective: 'IT/Tech Support',
  },

  // ── LA TROBE UNIVERSITY ─────────────────────────────────────────────────────
  {
    id: 'latrobe_followup_items_0526',
    date: '2026-05-26',
    subject: '[FOLLOWUP] Items from meeting — La Trobe',
    institution: 'La Trobe University',
    primaryEmail: 's.midford@latrobe.edu.au',
    recipients: ['s.midford@latrobe.edu.au', 's.kavar@latrobe.edu.au'],
    summary: 'Kim Burdett post-meeting follow-up to Shainal Kavar and Sarah Midford. Items: PDF Spaces demo materials, AI tool access, and partnership next steps. Al CC\'d.',
    objective: 'AI Innovation and Leadership',
  },
  {
    id: 'latrobe_checkin_meeting_0518',
    date: '2026-05-18',
    subject: 'Adobe & La Trobe Partnership Check-in meeting',
    institution: 'La Trobe University',
    primaryEmail: 'K.Bosnjak@latrobe.edu.au',
    recipients: ['K.Bosnjak@latrobe.edu.au'],
    summary: 'Katarina Bosnjak (Operations Coordinator, PVC Learning & Teaching) scheduling partnership check-in at Sarah Kavar\'s request. Attendees: Fiona Bird, Jay Glaysier, Emma White, Ian Wedlock and others. Time confirmed.',
    objective: 'Awareness',
  },
  {
    id: 'latrobe_pat_mclaughlin_0511',
    date: '2026-05-11',
    subject: 'Hello and heads up — La Trobe',
    institution: 'La Trobe University',
    primaryEmail: 'P.McLaughlin@latrobe.edu.au',
    recipients: ['P.McLaughlin@latrobe.edu.au'],
    summary: 'Pat McLaughlin sharing LTU\'s framework for integrating AI into ~50 first-year subjects (project led by Sarah). Flagging IT contact Reece Mathieson for Creative Cloud access queries. Good catch-up after campus visit.',
    objective: 'AI Innovation and Leadership',
  },
  {
    id: 'latrobe_student_spaces_beta_0419',
    date: '2026-04-19',
    subject: '[Beta is now Live] Student Spaces + AI Tools for education',
    institution: 'La Trobe University',
    primaryEmail: 's.kavar@latrobe.edu.au',
    recipients: ['s.kavar@latrobe.edu.au', 'm.tanti@latrobe.edu.au'],
    summary: 'Kim announcing Student Spaces beta is live. Sent to Shainal Kavar and Miriam Tanti at La Trobe, following their US study tour exposure to early beta.',
    objective: 'AI Innovation and Leadership',
  },
  {
    id: 'latrobe_study_tour_thankyou_0425',
    date: '2026-04-25',
    subject: 'Thank you for joining us — Education Leadership Study Tour',
    institution: 'La Trobe University',
    primaryEmail: 's.midford@latrobe.edu.au',
    recipients: ['s.midford@latrobe.edu.au'],
    summary: 'Kim\'s thank you to Sarah Midford following the US Education Leadership Study Tour. Sarah replied warmly — grateful for the experience and the people met.',
    objective: 'Awareness',
  },
  {
    id: 'latrobe_matt_cooke_0417',
    date: '2026-04-17',
    subject: 'La Trobe / Adobe Next Steps',
    institution: 'La Trobe University',
    primaryEmail: 'M.Cooke2@latrobe.edu.au',
    recipients: ['M.Cooke2@latrobe.edu.au'],
    summary: 'Matt Cooke confirming catch-up meeting for 30 April at 3pm to discuss next steps — questions cover access, roadmap and possible deeper partnership.',
    objective: 'Awareness',
  },
  {
    id: 'latrobe_teams_channel_0415',
    date: '2026-04-15',
    subject: 'La Trobe Adobe Multimedia Teams channel',
    institution: 'La Trobe University',
    primaryEmail: 'V.Renolds@latrobe.edu.au',
    recipients: ['V.Renolds@latrobe.edu.au', 'P.McLaughlin@latrobe.edu.au'],
    summary: 'Victor Renolds added Al to the O365-Adobe Multimedia La Trobe Teams channel (7 members). Good ongoing collaboration channel now active.',
    objective: 'Staff and Student Engagement',
  },

  // ── UNIVERSITY OF WESTERN AUSTRALIA ─────────────────────────────────────────
  {
    id: 'uwa_planning_alyce_0529',
    date: '2026-05-29',
    subject: 'UWA - Adobe planning',
    institution: 'University of Western Australia',
    primaryEmail: 'alyce-maree.mcgillivray@uwa.edu.au',
    recipients: ['alyce-maree.mcgillivray@uwa.edu.au'],
    summary: 'Alyce-Maree McGillivray in contact regarding Adobe planning and upcoming UWA partnership activity.',
    objective: 'Awareness',
  },
  {
    id: 'uwa_mutual_success_0527',
    date: '2026-05-27',
    subject: 'Mutual Success Plan and Adobe handover tasks',
    institution: 'University of Western Australia',
    primaryEmail: 'sandra.houghton@uwa.edu.au',
    recipients: ['sandra.houghton@uwa.edu.au'],
    summary: 'Confirming June 1 meeting with Sandra Houghton. Update on Student Life conversation re partnership support from their side.',
    objective: 'Awareness',
  },
  {
    id: 'uwa_oday_alison_0529',
    date: '2026-05-29',
    subject: 'UWA - Adobe Creative Campus - O-Day support',
    institution: 'University of Western Australia',
    primaryEmail: 'alison.cridge@guild.uwa.edu.au',
    recipients: ['alison.cridge@guild.uwa.edu.au'],
    summary: 'Teams meeting scheduled for 10am Perth time with Alison Cridge (UWA Guild) to discuss O-Day Creative Campus activation and student engagement.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'uwa_portal_elise_0526',
    date: '2026-05-26',
    subject: 'Adobe Portal Support role — UWA',
    institution: 'University of Western Australia',
    primaryEmail: 'elise.richards@uwa.edu.au',
    recipients: ['elise.richards@uwa.edu.au'],
    summary: 'Clarifying with Elise Richards that there is no limit on 30-minute expert portal sessions available to UWA staff.',
    objective: 'IT/Tech Support',
  },

  // ── RMIT UNIVERSITY ──────────────────────────────────────────────────────────
  {
    id: 'rmit_vexite_presentations_0601',
    date: '2026-06-01',
    subject: 'VE x ITE presentations',
    institution: 'RMIT University',
    primaryEmail: 'clare.dyson@rmit.edu.au',
    recipients: ['clare.dyson@rmit.edu.au'],
    summary: 'Calendar acceptance for VE x ITE student presentations at RMIT. Al confirming attendance.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'rmit_industry_cluster_pd_0602',
    date: '2026-06-02',
    subject: 'Industry Cluster PD Day',
    institution: 'RMIT University',
    primaryEmail: 'kirsty.tod@rmit.edu.au',
    recipients: ['kirsty.tod@rmit.edu.au'],
    summary: 'Kirsty Tod at RMIT reaching out regarding Industry Cluster Professional Development Day. Adobe involvement being discussed.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'rmit_monday_clare_0529',
    date: '2026-05-29',
    subject: 'Re: Monday — RMIT student presentations',
    institution: 'RMIT University',
    primaryEmail: 'clare.dyson@rmit.edu.au',
    recipients: ['clare.dyson@rmit.edu.au'],
    summary: 'Confirming availability to attend RMIT student presentations. Will step out of 12:30 meeting early to attend.',
    objective: 'Staff and Student Engagement',
  },

  // ── SWINBURNE UNIVERSITY ────────────────────────────────────────────────────
  {
    id: 'swin_pdf_spaces_decline_0525',
    date: '2026-05-25',
    subject: 'Swinburne - Adobe - PDF Spaces Pilot Discussion',
    institution: 'Swinburne University',
    primaryEmail: 'rulbrick@swin.edu.au',
    recipients: ['rulbrick@swin.edu.au', 'rgerrard@swin.edu.au'],
    summary: 'Rowena Ulbrick declined and rescheduled the PDF Spaces pilot meeting. Sent a detailed RE explaining the delay. Following up with Rohan Gerrard on new availability.',
    objective: 'IT/Tech Support',
  },
  {
    id: 'swin_digital_coaches_credits_0519',
    date: '2026-05-19',
    subject: 'Additional Credits for Adobe Digital Coaches',
    institution: 'Swinburne University',
    primaryEmail: 'rgerrard@swin.edu.au',
    recipients: ['rgerrard@swin.edu.au'],
    summary: 'Rohan Gerrard following up on additional license credits for Adobe Digital Coaches program at Swinburne. Active thread around credit allocation.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'swin_teams_recording_0518',
    date: '2026-05-18',
    subject: 'Teams Recording — Swinburne webinar',
    institution: 'Swinburne University',
    primaryEmail: 'rulbrick@swin.edu.au',
    recipients: ['rulbrick@swin.edu.au'],
    summary: 'Rowena Ulbrick requesting the Teams recording from the 6 May AI Ready Campus webinar. Multiple follow-ups resolved.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'swin_applause_0511',
    date: '2026-05-11',
    subject: 'A round of applause and appreciation — Swinburne',
    institution: 'Swinburne University',
    primaryEmail: 'rulbrick@swin.edu.au',
    recipients: ['rulbrick@swin.edu.au'],
    summary: 'Rowena Ulbrick sharing formal recognition and appreciation for the Adobe-Swinburne partnership work. Attached supporting documentation. Positive relationship milestone.',
    objective: 'Awareness',
  },
  {
    id: 'swin_thank_you_0506',
    date: '2026-05-06',
    subject: 'Thank you — Swinburne post-webinar',
    institution: 'Swinburne University',
    primaryEmail: 'rulbrick@swin.edu.au',
    recipients: ['rulbrick@swin.edu.au', 'lmann@swin.edu.au'],
    summary: 'Rowena Ulbrick and Lauren Mann thanking Al and team following the 6 May webinar. Strong positive response from Swinburne side.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'swin_6may_webinar_0506',
    date: '2026-05-06',
    subject: '6 May Webinar — Swinburne AI Ready Campus',
    institution: 'Swinburne University',
    primaryEmail: 'rulbrick@swin.edu.au',
    recipients: ['rulbrick@swin.edu.au'],
    summary: 'Multiple logistical exchanges with Rowena Ulbrick ahead of the 6 May webinar on Building an Equitable, AI Ready Campus. Swinburne featuring as the case study institution.',
    objective: 'AI Innovation and Leadership',
  },
  {
    id: 'swin_webinar_ai_ready_0423',
    date: '2026-04-23',
    subject: 'Webinar: Building an Equitable AI Ready Campus — registration live',
    institution: 'Swinburne University',
    primaryEmail: 'rulbrick@swin.edu.au',
    recipients: ['rulbrick@swin.edu.au'],
    summary: 'Rowena Ulbrick confirming Swinburne involvement in the AI Ready Campus webinar. Adobe webinar preparation and planning with Tyronne O\'Callaghan and Sanna Eskelinen.',
    objective: 'AI Innovation and Leadership',
  },
  {
    id: 'swin_student_spaces_0414',
    date: '2026-04-14',
    subject: 'Student Spaces is now live — Swinburne',
    institution: 'Swinburne University',
    primaryEmail: 'rulbrick@swin.edu.au',
    recipients: ['rulbrick@swin.edu.au'],
    summary: 'Rowena Ulbrick responding positively to Student Spaces go-live announcement.',
    objective: 'AI Innovation and Leadership',
  },
  {
    id: 'swin_collab_lab_0401',
    date: '2026-04-01',
    subject: 'Collaboration Lab student session attendees',
    institution: 'Swinburne University',
    primaryEmail: 'rgerrard@swin.edu.au',
    recipients: ['rgerrard@swin.edu.au'],
    summary: 'Rohan Gerrard sending attendee list for the Collaboration Lab student session. Manuela Franceschini and Al coordinating the session with Swinburne.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'swin_educator_lab_0401',
    date: '2026-04-01',
    subject: 'Educator Collaborator Lab attendees',
    institution: 'Swinburne University',
    primaryEmail: 'rgerrard@swin.edu.au',
    recipients: ['rgerrard@swin.edu.au'],
    summary: 'Rohan Gerrard sharing attendee list for the Educator Collaborator Lab session at Swinburne.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'swin_innovator_accelerator_0331',
    date: '2026-03-31',
    subject: 'Swinburne University — Innovator Accelerator Fund Application',
    institution: 'Swinburne University',
    primaryEmail: 'rulbrick@swin.edu.au',
    recipients: ['rulbrick@swin.edu.au'],
    summary: 'Swinburne recognised as an inaugural Adobe Creative Campus Innovator. Innovator Accelerator Fund application submitted. Helen Lacey coordinating approval.',
    objective: 'AI Innovation and Leadership',
  },


  // ── TORRENS UNIVERSITY & MEDIA DESIGN SCHOOL ─────────────────────────────────
  {
    id: 'torrens_quick_question_0602',
    date: '2026-06-02',
    subject: 'Quick question — Torrens',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'benay.ellison@Torrens.edu.au',
    recipients: ['benay.ellison@Torrens.edu.au'],
    summary: 'Benay Ellison reaching out with a quick question regarding Adobe tools or support.',
    objective: 'Awareness',
  },
  {
    id: 'torrens_mutual_success_plan_0521',
    date: '2026-05-21',
    subject: 'Torrens - Adobe Mutual Success Plan',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'esimon@Torrens.edu.au',
    recipients: ['esimon@Torrens.edu.au'],
    summary: 'E. Simon at Torrens confirming details around the Mutual Success Plan discussion. Active planning thread.',
    objective: 'Awareness',
  },
  {
    id: 'mds_pitch_form_0521',
    date: '2026-05-21',
    subject: 'Pitch form — Media Design School',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'don.chooi@mediadesignschool.com',
    recipients: ['don.chooi@mediadesignschool.com'],
    summary: 'Don Chooi (MDS) sending through pitch form with attachment. Likely related to a student or industry pitch event collaboration with Adobe.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'torrens_adobe_pro_migration_0520',
    date: '2026-05-20',
    subject: 'Adobe Pro Migration for Social Media Team',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'juliana.rodriguez@torrens.edu.au',
    recipients: ['juliana.rodriguez@torrens.edu.au'],
    summary: 'Juliana Rodriguez requesting support for migrating the Torrens Social Media Team to Adobe Pro. Rosie Sue (Adobe Solutions Consultant) assisting with technical resolution.',
    objective: 'IT/Tech Support',
  },
  {
    id: 'torrens_msp_preread_0514',
    date: '2026-05-14',
    subject: 'TUA Adobe Mutual Success Plan — pre-read',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'esimon@Torrens.edu.au',
    recipients: ['esimon@Torrens.edu.au', 'selene.martinez-pacheco@Torrens.edu.au'],
    summary: 'E. Simon sending pre-read materials ahead of Torrens-Adobe Mutual Success Plan meeting. Selene Martinez-Pacheco also responding. Active planning for partnership review.',
    objective: 'Awareness',
  },
  {
    id: 'torrens_meeting_tomorrow_0514',
    date: '2026-05-14',
    subject: 'Torrens-Adobe meeting tomorrow',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'nscoular@torrens.edu.au',
    recipients: ['nscoular@torrens.edu.au'],
    summary: 'N. Scoular confirming Torrens-Adobe meeting logistics. Active coordination ahead of partnership review session.',
    objective: 'Awareness',
  },
  {
    id: 'torrens_fashion_cads_0513',
    date: '2026-05-13',
    subject: 'Adobe AI capabilities — Fashion CADs',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'esimon@Torrens.edu.au',
    recipients: ['esimon@Torrens.edu.au', 'rponting@Torrens.edu.au'],
    summary: 'E. Simon and R. Ponting exploring Adobe AI capabilities for Fashion CAD workflows. Extended thread with multiple replies exploring Firefly and generative tools for fashion design education.',
    objective: 'AI Innovation and Leadership',
  },
  {
    id: 'torrens_innovation_cafe_query_0513',
    date: '2026-05-13',
    subject: 'Torrens participation @ Innovation Café — query',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'selene.martinez-pacheco@Torrens.edu.au',
    recipients: ['selene.martinez-pacheco@Torrens.edu.au'],
    summary: 'Selene Martinez-Pacheco querying Torrens\'s participation arrangements for the Innovation Café event.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'torrens_express_poster_workshop_0508',
    date: '2026-05-08',
    subject: 'Adobe Express poster design workshop next week',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'benay.ellison@Torrens.edu.au',
    recipients: ['benay.ellison@Torrens.edu.au'],
    summary: 'Benay Ellison coordinating the Adobe Express poster design workshop at Torrens. Multiple planning exchanges leading up to the session.',
    objective: 'Curriculum Support',
  },
  {
    id: 'mds_pres_morning_0505',
    date: '2026-05-05',
    subject: 'Adobe presentation this morning — MDS',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'jim.murray@mediadesignschool.com',
    recipients: ['jim.murray@mediadesignschool.com'],
    summary: 'Jim Murray (MDS) following up after Adobe presentation at Media Design School. Positive response.',
    objective: 'Awareness',
  },
  {
    id: 'mds_creative_campus_agreement_0518',
    date: '2026-05-18',
    subject: 'Adobe Creative Campus Agreement — Media Design School',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'jim.murray@mediadesignschool.com',
    recipients: ['jim.murray@mediadesignschool.com'],
    summary: 'Jim Murray (MDS Director) sending through the Adobe Creative Campus Agreement for review and sign-off. Kim Burdett coordinating.',
    objective: 'Awareness',
  },
  {
    id: 'torrens_msp_active_0430',
    date: '2026-04-30',
    subject: 'Torrens / Adobe Mutual Success Plan',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'nscoular@Torrens.edu.au',
    recipients: ['nscoular@Torrens.edu.au'],
    summary: 'N. Scoular (Torrens) actively engaged on Mutual Success Plan. Multiple exchanges across late April confirming scope and participants.',
    objective: 'Awareness',
  },
  {
    id: 'torrens_express_license_0422',
    date: '2026-04-22',
    subject: 'Torrens Adobe Express License Discussion',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'nscoular@torrens.edu.au',
    recipients: ['nscoular@torrens.edu.au'],
    summary: 'Complex licensing discussion with N. Scoular regarding Adobe Express deployment across Torrens. Harry K and Sanna Eskelinen from Adobe involved in resolving commercial terms.',
    objective: 'IT/Tech Support',
  },
  {
    id: 'torrens_session_inputs_0422',
    date: '2026-04-22',
    subject: 'Torrens session — inputs',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'selene.martinez-pacheco@Torrens.edu.au',
    recipients: ['selene.martinez-pacheco@Torrens.edu.au'],
    summary: 'Selene Martinez-Pacheco providing session inputs for upcoming Adobe-Torrens collaborative session.',
    objective: 'Curriculum Support',
  },
  {
    id: 'torrens_attribution_0424',
    date: '2026-04-24',
    subject: 'Attribution for Adobe images for educational purposes',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'rachel.smith1@torrens.edu.au',
    recipients: ['rachel.smith1@torrens.edu.au'],
    summary: 'Rachel Smith querying correct attribution requirements for Adobe stock images used in Torrens educational materials.',
    objective: 'Curriculum Support',
  },
  {
    id: 'mds_designer_day_0602',
    date: '2026-06-02',
    subject: 'Designer for a Day Event — follow up',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'ashley.boyd@mediadesignschool.com',
    recipients: ['ashley.boyd@mediadesignschool.com'],
    summary: 'Ashley Boyd (Media Design School) following up on Designer for a Day event. Ongoing collaboration on student industry exposure.',
    objective: 'Staff and Student Engagement',
  },
  {
    id: 'torrens_brand_kit_0518',
    date: '2026-05-18',
    subject: 'Adobe Express Brand Kit — Fonts, Licensing & Enterprise Availability',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'anukrit.gaur@torrens.edu.au',
    recipients: ['anukrit.gaur@torrens.edu.au', 'MCook@torrens.edu.au', 'dvasquez@torrens.edu.au'],
    summary: 'Anukrit Gaur and team querying custom font uploads, shared Brand Kits, and org-wide Adobe Express deployment under current Torrens licensing.',
    objective: 'IT/Tech Support',
  },
  {
    id: 'mds_aei_register_0513',
    date: '2026-05-13',
    subject: 'Register for Adobe Education Institute 2026 — MDS',
    institution: 'Torrens University & Media Design School',
    primaryEmail: 'jim.murray@mediadesignschool.com',
    recipients: ['jim.murray@mediadesignschool.com'],
    summary: 'Jim Murray (MDS) confirming registration for the Adobe Education Institute 2026 (May 18–21).',
    objective: 'Staff and Student Engagement',
  },

]